"""initial models

Revision ID: 29e1f21f3cc2
Revises: 
Create Date: 2018-09-27 19:46:22.963105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e1f21f3cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancerdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('true_value', sa.Integer(), nullable=True),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('var_one', sa.Float(), nullable=True),
    sa.Column('var_two', sa.Float(), nullable=True),
    sa.Column('var_three', sa.Float(), nullable=True),
    sa.Column('var_four', sa.Float(), nullable=True),
    sa.Column('var_five', sa.Float(), nullable=True),
    sa.Column('var_six', sa.Float(), nullable=True),
    sa.Column('var_seven', sa.Float(), nullable=True),
    sa.Column('var_eight', sa.Float(), nullable=True),
    sa.Column('var_nine', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('true_value', sa.Integer(), nullable=True),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('var_one', sa.Float(), nullable=True),
    sa.Column('var_two', sa.Float(), nullable=True),
    sa.Column('var_three', sa.Float(), nullable=True),
    sa.Column('var_four', sa.Float(), nullable=True),
    sa.Column('var_five', sa.Float(), nullable=True),
    sa.Column('var_six', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pnndata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('true_value', sa.Integer(), nullable=True),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('var_one', sa.Float(), nullable=True),
    sa.Column('var_two', sa.Float(), nullable=True),
    sa.Column('var_three', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pnndata')
    op.drop_table('epdata')
    op.drop_table('cancerdata')
    # ### end Alembic commands ###
